## gateway-rs configuration file

## Keypair is a string that supports specifying different locations for 
## the secrets. The default one is file based one since all devices 
## can support it.

# File based: 
keypair = "/etc/helium_gateway/gateway_key.bin"

# Ecc608 based:
# keypair = "ecc://i2c-1:96?slot=0"
# onboarding = "ecc://i2c-1:96?slot=15"

# The address to listen on for the (semtech) packet forwarder
listen = "127.0.0.1:1680"

# The local port to serve the local grpc on. Supports both a simple port number
# or full ip:port listen address. Do NOT expose this port outside of the host
# network for security
api = 4467

# The default region to use until a region is received from the Helium network.
# This value should line up with the configured region of the semtech packet
# forwarder. Note: Not setting this here or with a GW_REGION env var will stop
# packet and poc beaconing until the correct asserted region is retrieved. 
#
# region = "US915"

[log]
# The logging level to assume on startup
level = "info"
# Whether the logged output should include timestamps
timestamp = true

[poc]
# The uri to fetch entropy for poc beacons
entropy_uri = "http://entropy.iot.mainnet.helium.io:7080"
# The uri for IOT ingest services to deliver beacons and witnesses
ingest_uri = "http://mainnet-pociot.helium.io:9080"

# The config service is used to fetch and monitor region parameters and other
# configuration items
[config]
pubkey = "137oJzq1qZpSbzHawaysTGGsRCYTXG1MiTMQNxYSsQJp4YMDdN8"
uri = "http://mainnet-config.helium.io:6080/"

# The router uri is where lorawan packets are delivered to the helium packet
# router. 
[router]
uri = "http://mainnet-router.helium.io:8080/"
# Maximum number of packets to queue up for the packet router
queue = 20

